### ISSUE TITLE
Add pathway definitions

### ISSUE THREAD

**Issue by Ludee** [ReeemProject/reeem_db#6]
Include a table with pathway names and definitions (descriptions).

[reeem_db_pathways.sql](https://github.com/ReeemProject/reeem_db/blob/master/database_setup/reeem_db_pathways.sql)

**Comment by doroschmid** [comment]
Is it possible that the two columns "pathway" and "times_version" are switched in the database table reeem_pathway_schedule?

**Comment by Ludee** [comment]
Yes! That's right. There was a mix-up of these two columns.
The latest commit e767617 fixes it.
The db table is already updated. Thank you for the hint @doroschmid

**Comment by Ludee** [comment]
- [ ] Update pathway table after new naming structure #27
